### ISSUE TITLE
[BUG] Import error

### ISSUE THREAD

**Issue by joannadiong** [MartinHeroux/pliffy#20]
**Describe the bug**
Hi there. I followed the instructions on the [Installation guide](https://pliffy.readthedocs.io/en/latest/pages/first_steps.html) but received an error, reproduced below. Could you advise please? 
Many thanks

**To Reproduce**
Steps to reproduce the behaviour:
```python
>>> import pliffy
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/joanna/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.6397.98/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/joanna/Dropbox/Projects/anatomy/src/code/env/lib/python3.8/site-packages/pliffy/__init__.py", line 2, in <module>
    from . import plot
  File "/home/joanna/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.6397.98/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/joanna/Dropbox/Projects/anatomy/src/code/env/lib/python3.8/site-packages/pliffy/plot.py", line 1, in <module>
    from pliffy import estimate, parser, utils, figure
ImportError: cannot import name 'figure' from partially initialized module 'pliffy' (most likely due to a circular import) (/home/joanna/Dropbox/Projects/anatomy/src/code/env/lib/python3.8/site-packages/pliffy/__init__.py)
```

**Python:**
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] on linux

**Comment by MartinHeroux** [comment]
Thanks for pointing this out. Circular imports are not always easy to catch, and I found that they occurred more often given that I was using type-hinting. 

I am struggling to find a fix, but will continue to look into it. The problem seems to be with the packaging. 

If you don't mind helping me trouble shoot the problem, could you try running the following code in a Linux terminal.
```bash
git clone https://github.com/MartinHeroux/pliffy.git
cd pliffy/
python3 -m venv venv
source venv/bin/activate
python setup.py build
python setup.py install
python
```
```python
import pliffy
pliffy.demo.demo()
```

What is does is:
 - clones the pliffy github repo
- creates a dedicated python environment (and activates it)
- installs the local version of pliffy
- loads a python interpreter
- imports pliffy

I have done this on my computer and it works fine. 

Would you mind trying this and letting me know how you go?

**Comment by joannadiong** [comment]
Thank you. Yes, running the code in the Terminal generates printed output and graphs.

Quick comment: `pliffy` in the virtual env for this project is the broken version and is not "connected" to the updated main `pliffy`, or my updated forked `pliffy`. For now, I changed the project's interpreter to Python 3.8 in Anaconda, added my forked `pliffy` to root, removed the venv root, and `pliffy` successfully imported. I'm sure there's better ways to go about this, but am glad it works for now. Thanks for the support.

**Comment by MartinHeroux** [comment]
After a bit of digging and the help of some kind folks at [StackOverflow](https://stackoverflow.com/questions/65106077/python-importerror-most-likely-due-to-a-circular-import-for-pip-install-but-no?noredirect=1#comment115118271_65106077), this issue has been resolved.

Adding an import and changing a line of my setup.py file fixed things

```
from setuptools import find_packages 
...
packages=find_packages()

```
Version 0.1.3 of pliffy up on PyPi includes this change and now works.
