### ISSUE TITLE
[BUG] PliffyInfoABD unexpected keyword argument 'figure_name'

### ISSUE THREAD

**Issue by joannadiong** [MartinHeroux/pliffy#22]
**Describe the bug**
The how_to_guides.rst states to specify `figure_name` but utils.py line 134 requires `plot_name`. So running PliffyInfoABD following the docs instructions will generate the error above. I'd submit a pull request, but `figure_name` in text appears in a few places and I'm not sure which name is preferred. See what is best? Thanks.

**Comment by MartinHeroux** [comment]
Thanks for testing out the tutorials, etc. Clearly I made some of those documents, refactored a few names, then made more documents.

I would be included to keep the names in the actual package modules (utils.py), and change the documentation.

Are you happy to make the changes to the .rst files? And if you know how, to generate the HTML documentation via sphinx?

If so, great. If needed, I am happy to help if you run into issues, or if you need a bit of guidance of how to make the local branch, push to your fork, and then make a pull request.

If not, I can tackle the changes.

Let me know how you want to proceed.

**Comment by joannadiong** [comment]
Sure, happy to edit the .rst file and submit pull request, if you could talk me through sphinx part later. Will be good practice.

**Comment by MartinHeroux** [comment]
Issue resolved.
