### ISSUE TITLE
[FEATURE]: Citation style

### ISSUE THREAD

**Issue by joannadiong** [MartinHeroux/pliffy#24]
I'm trying to cite this (cool, and saves-me-so-much-work!) package, but am not used to citing software. 
Do you have a preferred list of things for citation, and have I missed the DOI somewhere?
Thanks, Jo

**Comment by joannadiong** [comment]
PS: To clarify, right now the within-group error bars all plot CI, right? (i.e. no function yet to plot SD) 
I could KIV as future enhancement to add functionality for plotting SD error bars

**Comment by MartinHeroux** [comment]
zenodo was used with doi.
